language: java
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - openjdk-8-jdk
jdk: openjdk8
script:
- mvn tests
- mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
